### ISSUE TITLE
precision-recall-summary.tsv formatting

### ISSUE THREAD

**Issue by nate-d-olson** [TimD1/vcfdist#15]
The precision-recall-summary.tsv header has an extra `\t` between PREC and RECALL as well as RECALL and F1_SCORE. Not sure if this is intentional.

Code with extra tabs in header

https://github.com/TimD1/vcfdist/blob/5cb2532ac2bbd82440aabffcf74e4535dba75ef6/src/print.cpp#L496
https://github.com/TimD1/vcfdist/blob/5cb2532ac2bbd82440aabffcf74e4535dba75ef6/src/print.cpp#L503

Also when the min and max QUAL are both 0 the tsv table has duplicate rows, would be nice to either include a note about this in the documentation or modify the code to limit the number of row output based on QUAL values in the QUERY vcf. This is arguably a unique issue to my comparison, I'm using a vcf generated by dipcall as TRUTH and PAV as QUERY.

**Comment by TimD1** [comment]
Thanks for mentioning this. The extra tab on line 503 is intentional (to align terminal output), but it shouldn't be present in line 496 (summary TSV). I'll fix this now, and take a look at the duplicated rows when min and max qual are 0.

**Comment by TimD1** [comment]
The duplicated rows are because the summary output reports metrics for both:
 - all variants
 - all variants passing the Q-score threshold which maximizes performance (best F1 score)

This was modeled after vcfeval's output. Instead of removing the second row when the minimum and maximum quality scores are both zero, I think I should just explicitly label the rows by adding a "THRESHOLD" column:

TYPE   THRESHOLD   MIN_QUAL   TRUTH_TP    QUERY_TP ...
SNP    NONE               0                     80001           80009         ...
SNP    BEST                 6                     80055           80065         ...

That way, there will still be two rows when the only quality threshold option is zero, but the meaning of each row is more clear (and consistent with when Q isn't always 0). Does that sound reasonable?

**Comment by nate-d-olson** [comment]
Thanks for the quick fix for the extra tabs in the head. 
The additional THRESHOLD column makes sense to me thanks!
