### ISSUE TITLE
Variant is same as truth, but assigned truth FN and query FP

### ISSUE THREAD

**Issue by mbhall88** [TimD1/vcfdist#22]
I have an unusual case where I have a variant in the vcfdist summary VCF which has a truth BD of FN and a query BD of FP.

Here is the vcfdist entry (with some context). The variant of interest is POS 1770515

```
chromosome_1    1770510 .       A       G       .       PASS    .       GT:BD:BC:RD:QD:BK:QQ:SC:SG:PS:PB:BS:FE  1:TP:1.000000:1:0:gm:0:13581:5:0:0:.:.  1:TP:1.000000:1:0:gm:4697:13581:5:0:0:0:0
chromosome_1    1770512 .       T       TC      .       PASS    .       GT:BD:BC:RD:QD:BK:QQ:SC:SG:PS:PB:BS:FE  1:FN:0.000000:1:1:.:0:13581:4:0:0:.:.   .:.:.:.:.:.:.:13581:.:.:0:.:.
chromosome_1    1770513 .       T       C       .       PASS    .       GT:BD:BC:RD:QD:BK:QQ:SC:SG:PS:PB:BS:FE  .:.:.:.:.:.:.:13581:.:.:0:.:.   1:FP:0.000000:.:.:.:4697:13581:2:0:0:0:0
chromosome_1    1770515 .       C       T       .       PASS    .       GT:BD:BC:RD:QD:BK:QQ:SC:SG:PS:PB:BS:FE  1:FN:0.500000:2:1:lm:0:13581:1:0:0:.:.  1:FP:0.500000:2:1:lm:4697:13581:1:0:0:0:0
chromosome_1    1770516 .       C       T       .       PASS    .       GT:BD:BC:RD:QD:BK:QQ:SC:SG:PS:PB:BS:FE  .:.:.:.:.:.:.:13581:.:.:0:.:.   1:FP:0.000000:.:.:.:4697:13581:0:0:0:0:0
chromosome_1    1770517 .       A       T       .       PASS    .       GT:BD:BC:RD:QD:BK:QQ:SC:SG:PS:PB:BS:FE  1:FN:0.500000:2:1:lm:0:13581:1:0:0:.:.  .:.:.:.:.:.:.:13581:.:.:0:.:.
```

Here is the context for this variant in the truth VCF

```
chromosome_1    1770510 d37c924f        A       G       .       PASS    .       GT      1
chromosome_1    1770512 e2a4cbea        T       TC      .       PASS    .       GT      1
chromosome_1    1770515 9a7ac0ad        C       T       .       PASS    .       GT      1
chromosome_1    1770517 3e922a93        A       T       .       PASS    .       GT      1
```

and the query VCF

```
chromosome_1    1770510 .       A       G       4697.14 PASS    AB=0;ABP=0;AC=2;AF=1;AN=2;AO=171;CIGAR=1X3M1X2M1I2M1X1M1X;DP=173;DPB=188.75;DPRA=0;EPP=15.2137;EPPR=0;GTI=0;LEN=13;MEANALT=2;MQM=59.4971;MQMR=0;NS=1;NUMALT=1;ODDS=240.275;PAIRED=0.976608;PAIREDR=0;PAO=8;PQA=270;PQR=0;PRO=0;QA=5569;QR=0;RO=0;RPL=151;RPP=220.932;RPPR=0;RPR=20;RUN=1;SAF=78;SAP=5.8675;SAR=93;SRF=0;SRP=0;SRR=0;TYPE=complex        GT:DP:AD:RO:QR:AO:QA:GL 1:173:0,171:0:0:171:5569:-499.353,-51.4761,0
chromosome_1    1770513 .       T       C       4697.14 PASS    AB=0;ABP=0;AC=2;AF=1;AN=2;AO=171;CIGAR=1X3M1X2M1I2M1X1M1X;DP=173;DPB=188.75;DPRA=0;EPP=15.2137;EPPR=0;GTI=0;LEN=13;MEANALT=2;MQM=59.4971;MQMR=0;NS=1;NUMALT=1;ODDS=240.275;PAIRED=0.976608;PAIREDR=0;PAO=8;PQA=270;PQR=0;PRO=0;QA=5569;QR=0;RO=0;RPL=151;RPP=220.932;RPPR=0;RPR=20;RUN=1;SAF=78;SAP=5.8675;SAR=93;SRF=0;SRP=0;SRR=0;TYPE=complex        GT:DP:AD:RO:QR:AO:QA:GL 1:173:0,171:0:0:171:5569:-499.353,-51.4761,0
chromosome_1    1770515 .       C       T       4697.14 PASS    AB=0;ABP=0;AC=2;AF=1;AN=2;AO=171;CIGAR=1X3M1X2M1I2M1X1M1X;DP=173;DPB=188.75;DPRA=0;EPP=15.2137;EPPR=0;GTI=0;LEN=13;MEANALT=2;MQM=59.4971;MQMR=0;NS=1;NUMALT=1;ODDS=240.275;PAIRED=0.976608;PAIREDR=0;PAO=8;PQA=270;PQR=0;PRO=0;QA=5569;QR=0;RO=0;RPL=151;RPP=220.932;RPPR=0;RPR=20;RUN=1;SAF=78;SAP=5.8675;SAR=93;SRF=0;SRP=0;SRR=0;TYPE=complex        GT:DP:AD:RO:QR:AO:QA:GL 1:173:0,171:0:0:171:5569:-499.353,-51.4761,0
chromosome_1    1770516 .       C       T       4697.14 PASS    AB=0;ABP=0;AC=2;AF=1;AN=2;AO=171;CIGAR=1X3M1X2M1I2M1X1M1X;DP=173;DPB=188.75;DPRA=0;EPP=15.2137;EPPR=0;GTI=0;LEN=13;MEANALT=2;MQM=59.4971;MQMR=0;NS=1;NUMALT=1;ODDS=240.275;PAIRED=0.976608;PAIREDR=0;PAO=8;PQA=270;PQR=0;PRO=0;QA=5569;QR=0;RO=0;RPL=151;RPP=220.932;RPPR=0;RPR=20;RUN=1;SAF=78;SAP=5.8675;SAR=93;SRF=0;SRP=0;SRR=0;TYPE=complex        GT:DP:AD:RO:QR:AO:QA:GL 1:173:0,171:0:0:171:5569:-499.353,-51.4761,0
```

The position 1770515 is exactly the same in the query as it is in the truth, so I am a little unsure why it has been classified in this way? I see it was given partial credit of 0.5 - shouldn't it be 1.0?

**Comment by TimD1** [comment]
This is occurring because the two substitutions at positions 515 and 517 are being considered a complex variant, instead of two independent substitutions.

The edit distance is reduced from 2 to 1 by correctly calling one of the two substitutions, but this is deemed insufficient (50% correct).

I was actually planning to release a vcfdist update later today that should consider variants within a complex variant independent when it can (which would probably change this evaluation to a FN sub and TP sub, as you likely expected).

**Comment by mbhall88** [comment]
Ahh I see. Let me know when the release is out and I’ll test it out on this sample

**Comment by TimD1** [comment]
Just released v2.5.0!

Has vcfdist's behavior on this example changed?  It will take a bit to update Docker and conda, so please install from source to test it out.

**Comment by mbhall88** [comment]
Thanks for the quick turnaround Tim.

The behaviour has changed slightly, in that the partial credit seems to now be 0.333

```
chromosome_1    1770510 .       A       G       .       PASS    .       GT:BD:BC:RD:QD:BK:QQ:SC:SG:PS:PB:BS:FE  1:TP:1.000000:1:0:gm:0:13581:1:0:0:.:.  1:TP:1.000000:1:0:gm:4697:13581:1:0:0:0:0
chromosome_1    1770512 .       T       TC      .       PASS    .       GT:BD:BC:RD:QD:BK:QQ:SC:SG:PS:PB:BS:FE  1:FN:0.333333:3:2:lm:0:13581:0:0:0:.:.  .:.:.:.:.:.:.:13581:.:.:0:.:.
chromosome_1    1770513 .       T       C       .       PASS    .       GT:BD:BC:RD:QD:BK:QQ:SC:SG:PS:PB:BS:FE  .:.:.:.:.:.:.:13581:.:.:0:.:.   1:FP:0.333333:3:2:lm:4697:13581:0:0:0:0:0
chromosome_1    1770515 .       C       T       .       PASS    .       GT:BD:BC:RD:QD:BK:QQ:SC:SG:PS:PB:BS:FE  1:FN:0.333333:3:2:lm:0:13581:0:0:0:.:.  1:FP:0.333333:3:2:lm:4697:13581:0:0:0:0:0
chromosome_1    1770516 .       C       T       .       PASS    .       GT:BD:BC:RD:QD:BK:QQ:SC:SG:PS:PB:BS:FE  .:.:.:.:.:.:.:13581:.:.:0:.:.   1:FP:0.333333:3:2:lm:4697:13581:0:0:0:0:0
chromosome_1    1770517 .       A       T       .       PASS    .       GT:BD:BC:RD:QD:BK:QQ:SC:SG:PS:PB:BS:FE  1:FN:0.333333:3:2:lm:0:13581:0:0:0:.:.  .:.:.:.:.:.:.:13581:.:.:0:.:.
```

**Comment by mbhall88** [comment]
Yeah, well I guess this exactly perfectly illustrates the massive importance of your work here. I think people don't appreciate the huge importance of variant assessment and just how complex it is. I think vcfdist has been one of the most important paper (for me) in the last year or two. Variant calls underpin so many of our important applications, so getting the best classifications it so vital.

Your logic re: distance between the sequences is sound, and maybe we need to move towards such distance metrics as a field, but the chances of that happening anytime soon are sadly slim.

For context also, here is the hap.py output for this region

```
chromosome_1    1770510 .       A       G       4697.14 .       BS=1770471      GT:BD:BK:BI:BVT:BLT:QQ  1/1:TP:gm:ti:SNP:homalt:4697.14 1/1:TP:gm:ti:SNP:homalt:4697.14
chromosome_1    1770512 .       T       TC      0       .       BS=1770471      GT:BD:BK:BI:BVT:BLT:QQ  1/1:FN:lm:i1_5:INDEL:homalt:.   ./.:.:.:.:NOCALL:nocall:0
chromosome_1    1770513 .       T       C       4697.14 .       BS=1770471      GT:BD:BK:BI:BVT:BLT:QQ  ./.:.:.:.:NOCALL:nocall:.       1/1:FP:lm:ti:SNP:homalt:4697.14
chromosome_1    1770515 .       C       T       4697.14 .       BS=1770471      GT:BD:BK:BI:BVT:BLT:QQ  1/1:TP:gm:ti:SNP:homalt:4697.14 1/1:TP:gm:ti:SNP:homalt:4697.14
chromosome_1    1770516 .       C       T       4697.14 .       BS=1770471      GT:BD:BK:BI:BVT:BLT:QQ  ./.:.:.:.:NOCALL:nocall:.       1/1:FP:lm:ti:SNP:homalt:4697.14
chromosome_1    1770517 .       A       T       0       .       BS=1770471      GT:BD:BK:BI:BVT:BLT:QQ  1/1:FN:lm:tv:SNP:homalt:.       ./.:.:.:.:NOCALL:nocall:0
```

**Comment by mbhall88** [comment]
I wonder if you might be able to comment on why hap.py is able to get this “right”?

I would be nice to at least replicate the “right” results from hap.py. But I appreciate that it not so simple. I suspect others might be hesitant to switch to vcfdist in such circumstances. 

I am currently working on a big variant calling benchmark for bacterial Nanopore sequencing data and these errors do make me a tiny bit nervous. I’m currently using vcfdist in my assessment pipeline, but it would be nice to clear this up for my peace of mind

**Comment by TimD1** [comment]
Sure! hap.py has no notion of complex variants nor partially-correct variants. It simply finds the largest subsets of truth and query variants that result in the exact same sequence. In other words, because hap.py doesn't consider inexact matches, it's equivalent to a version of vcfdist where the "alignment path" is forced to always pass through the reference sequence or a variant (and only matches are allowed). As a result, identifying TP/FP for individual variants is easy. 

Because vcfdist allows inexact matches, the best alignment may pass through several variants (with edits) before returning to the reference sequence. In such a case where the alignment goes off the "expected path" of the reference sequence and called variants (i.e. a complex variant), the edits on that path can't be assigned to a specific variant out of the several on that path. Unfortunately, I don't think there is a good way to guarantee finding variant-level equivalence without losing what makes vcfdist a great benchmarking tool: discovery of inexact matches and nearly equivalent variant representations.

I understand that, at first glance, this example is worrying. However, this will only occur within complex variants (which are rare), and I would argue that calling a subset of a complex variant a TP is not really "more correct". This will never occur for isolated SNPs. Overall, there are far more cases where hap.py reports a FP and FN but vcfdist identifies a TP (Figures 6 and 7 of our [new pre-print](https://www.biorxiv.org/content/10.1101/2024.01.23.575922v1.full.pdf)). For example, hap.py is unable to call any inexact matches TP, and skips evaluating some regions altogether due to complexity. Hope this summary helps!

**Comment by mbhall88** [comment]
Thanks for the detailed response. Yes trying to match coordinates between different paths in that way is an age old problem. Your justifications are sound and make a lot of sense.
