### ISSUE TITLE
What about hap.py xcmp?

### ISSUE THREAD

**Issue by jdidion** [TimD1/vcfdist#3]
In the preprint you seem to suggest that vcfdist is the first tool to allow partial credit, but `xcmp` has had that option for a long time. I suggest citing the hap.py github repo (https://github.com/Illumina/hap.py) as they did in the Krusche et al. Nat Biotech paper. I also suggest benchmarking against `xcmp` in addition to `vcfeval`.

**Comment by TimD1** [comment]
First of all, thanks for starting a discussion on this. 

**1. Citation:** In our pre-print, we cited the accompanying paper _"Best practices for benchmarking germline small-variant calls in human genomes"_ rather than the `hap.py` Github repo directly. I've made a note to also cite the Github repo in the final paper version; this could be useful to readers and we want to make sure proper credit is attributed.

**2. Partial Credit** Our pre-print's claim is somewhat confusing due to the fact that there are multiple ways to define "partial credit". Supplementary Note 2 from the above paper states:

> When benchmarking, these variant representation differences can also give rise to different notions of giving partial credit for variant calls, such as when a method calls only one SNV in a multi-nucleotide variant (MNV, defined as multiple, adjacent SNVs). When assigning TP/FP/FN status on a per-VCF-record basis, a variant caller that chooses to represent calls using single MNP records would not get credit for calling this SNV correctly since the overall MNP record does not produce the correct haplotype.

To the best of my knowledge, `xcmp` only attributes partial credit to MNPs by splitting them into SNPs. In contrast, our tool determines partial credit by the reduction in total edit distance when considering variants to be TPs vs FPs. It applies to MNPs, nearby SNPs, isolated or neighboring INDELs, or complex variants. In other words, we give 80% credit for calling a deletion of length 4 instead of 5 (Whether or not this is the best way to represent variant calling performance is up for debate). I do not believe `xcmp` does anything similar in this regard, and appears to be restricted to MNPs. If this is not the case, could you point me towards documentation regarding their methods? 

**3. Benchmarking** Supplementary Note 2 from the paper says:

> Our tools [`xcmp`] attempt to give partial credit when possible, and we generally recommend using vcfeval as the comparator to provide the most partial matches.

Most sources seemed to support using vcfeval as the standard comparison tool, which is why we selected it for our baseline in the paper. But `xcmp` does appear to support evaluating phased variant callsets, which might make it worth adding to our paper.

**Comment by jdidion** [comment]
Thanks!

2. These are helpful details - might be worth adding to the paper even if it's just a section in the supplement.
3. Personally I'd find it helpful to include `xcmp` in the benchmarks as I've found it can give better results than `vcfeval` in some situations. I'd like to replace my usage of hap.py with vcfdist and this would help to support that decision. But I understand you may have limited time and space for additional analyses.

**Comment by TimD1** [comment]
2. You might be interested in the last two paragraphs (pg 17) of the "Precision and recall calculations" section of the "Online Methods" section. I should probably pull this out under a separate subheading "Partial Credit" to increase visibility.
3. Yeah, I may or may not get around to doing this, but it would be a nice benchmark to have. I'll keep this issue open for now, and see if I have time later this week.

**Comment by jdidion** [comment]
Thanks again! Yes that section is helpful, and I do agree it might be better under a separate heading. But I was referring to the details about how partial credit differs in vcfdist vs xcmp. Others might be interested in that information as well.
