### ISSUE TITLE
Switch and Flip Error rates

### ISSUE THREAD

**Issue by rickymagner** [TimD1/vcfdist#33]
Hi, thanks for the tool. I wanted to try using it for some experiments in comparing phasing across some different software experimental groups. I noticed that the tool only outputs raw switch error/flip error counts, rather than rates (as a ratio of all phased variants, or something else). Is this intentional? I'm trying to understand the algorithms a bit more, but wanted to ask if it'd be a bad idea to take these raw counts and divide by e.g. the number of phased variants or the number of total variants in my query (or maybe the number of superclusters?) in order to compare these across software pipelines where the number of called variants might also vary, given that's a confounding factor in phasing performance.

On a separate note, I wanted to check I'm understanding the `NG_50` statistic properly. Does a value of say 20,000 mean that 50% of the variants across the whole genome are contained in a phase block of length >= 20,000? Or just the het variants? Or something else? 

Thanks!

**Comment by TimD1** [comment]
**1. switch and flip error rates vs raw counts**
Yes, it would be reasonable to divide these raw counts by the total number of superclusters to get the supercluster flip/switch error rates. This is [already done and the results are printed to the command line](https://github.com/TimD1/vcfdist/blob/39f4c242623ccbeb58cf073655a49d4d7fe7ef1e/src/phase.cpp#L392) by default (unless you set `--verbosity 0`), but isn't included in the `phasing-summary.tsv` because the metric isn't ideal (it's per-supercluster, not per-variant). I'm excited for the next major vcfdist release, which will allow per-variant metrics. I'll be sure to add the rates to `phasing-summary.tsv` for that next major release.

**2. NG50 statistic**
NG50 is not calculated based on the percentage of variants, but the size of the region the phase block covers. You may find the [Phasing Analysis page of the  wiki](https://github.com/TimD1/vcfdist/wiki/07-Phasing-Analysis) helpful:

> Phase set NG50 is the largest phased region such that all phased regions of that size and larger cover at least 50% of the genome.

**Comment by rickymagner** [comment]
1. That definitely sounds useful so looking forward to the next release. I run the tool through a workflow so parsing the command line output across various samples would be a headache. Though thinking about this a bit more, wouldn't it make more sense to divide by the number of het sites so the metric remains ambivalent to the amount of hom variants? Or maybe I missed that superclusters end up ignoring hom variants?

2. I was a little confused by that line so wanted some clarification. I think I'm still a little confused about how the "50% of the genome" is computed. Does this mean that if `N = NG_50` then 50% of bases in the reference are covered by a phase block of size >= N?

**Comment by rickymagner** [comment]
Sorry, I also had another question:

3. When looking at precision / recall stats, I know the docs say that non-phased variants are ignored. But are TPs labeled as such for matching the allele *and* having "correct" phasing information? I was trying to understand the description from [here](https://github.com/TimD1/vcfdist/wiki/06-Precision-and-Recall) but am having trouble relating it to what would happen in the simplest case, particularly if a TP in the "easy" isolated variant case means good alleles + genotypes + phasing, or just the first two. If a site gets labeled for a switch error / flip error, would that make it a FP automatically?

**Comment by TimD1** [comment]
1. Yes, the metric is not ideal, which is why it is not currently included in the output. A supercluster can include one or several het and/or hom variants.
2. Yes, that interpretation is correct.
3. A TP means the allele is correct. Flip errors do not automatically make a variant a FP. Also, please note that all homozygous variants are [split into two variants](https://github.com/TimD1/vcfdist/wiki/11-Implementation-Notes#homozygous-variant-counting) prior to vcfdist evaluation.

**Comment by rickymagner** [comment]
Thanks for the clarifications, and for the reminder about splitting hom sites into two hets for the purpose of labeling TP/FP, so that makes sense it's essentially an "allele" match but broken down by haplotype.
